// Generated by scripts/train_ctr_model.mjs. Do not edit by hand.
window.REDNOTE_CTR_MODEL = {
  "version": "offline-ctr-v1",
  "generatedAt": "2026-05-28T07:20:39.017Z",
  "source": "data/samples.csv",
  "sampleCount": 8,
  "featureKeys": [
    "brightness",
    "saturation",
    "contrast",
    "warm",
    "titleHook",
    "hasFace",
    "hasBeforeAfter"
  ],
  "weights": {
    "brightness": 0,
    "saturation": 0,
    "contrast": 0,
    "warm": 0,
    "titleHook": 0.4253,
    "hasFace": 0.2012,
    "hasBeforeAfter": 0.3735
  },
  "baselineCtr": 9.57,
  "minCtr": 7.6,
  "maxCtr": 11.6,
  "highCtrProfile": {
    "sampleCount": 3,
    "avgCtr": 10.87,
    "features": {
      "brightness": 60,
      "saturation": 60,
      "contrast": 60,
      "warm": 50,
      "titleHook": 56,
      "hasFace": 100,
      "hasBeforeAfter": 100
    },
    "examples": [
      {
        "name": "抗衰前后真实反馈",
        "ctr": 11.6,
        "tags": [
          "人物主体",
          "对比展示"
        ]
      },
      {
        "name": "热玛吉术前避坑清单",
        "ctr": 10.8,
        "tags": [
          "人物主体",
          "对比展示",
          "避坑内容",
          "术前决策"
        ]
      },
      {
        "name": "法令纹改善真实变化",
        "ctr": 10.2,
        "tags": [
          "人物主体",
          "对比展示"
        ]
      }
    ]
  },
  "samples": [
    {
      "id": "sample-01.svg",
      "sourceId": "sample-01.svg",
      "name": "热玛吉术前避坑清单",
      "title": "热玛吉术前避坑清单",
      "project": "热玛吉/抗衰",
      "ctr": 10.8,
      "features": {
        "brightness": 60,
        "saturation": 60,
        "contrast": 60,
        "warm": 50,
        "titleHook": 59,
        "hasFace": 100,
        "hasBeforeAfter": 100
      },
      "tags": [
        "人物主体",
        "对比展示",
        "避坑内容",
        "术前决策"
      ]
    },
    {
      "id": "sample-02.svg",
      "sourceId": "sample-02.svg",
      "name": "抗衰前后真实反馈",
      "title": "抗衰前后真实反馈",
      "project": "抗衰",
      "ctr": 11.6,
      "features": {
        "brightness": 60,
        "saturation": 60,
        "contrast": 60,
        "warm": 50,
        "titleHook": 59,
        "hasFace": 100,
        "hasBeforeAfter": 100
      },
      "tags": [
        "人物主体",
        "对比展示"
      ]
    },
    {
      "id": "sample-03.svg",
      "sourceId": "sample-03.svg",
      "name": "水光新手功课",
      "title": "水光新手功课",
      "project": "水光针",
      "ctr": 8.9,
      "features": {
        "brightness": 60,
        "saturation": 60,
        "contrast": 60,
        "warm": 50,
        "titleHook": 44,
        "hasFace": 100,
        "hasBeforeAfter": 0
      },
      "tags": [
        "人物主体"
      ]
    },
    {
      "id": "sample-04.svg",
      "sourceId": "sample-04.svg",
      "name": "面诊必须问的问题",
      "title": "面诊必须问的问题",
      "project": "面诊",
      "ctr": 9.4,
      "features": {
        "brightness": 60,
        "saturation": 60,
        "contrast": 60,
        "warm": 50,
        "titleHook": 49,
        "hasFace": 0,
        "hasBeforeAfter": 0
      },
      "tags": []
    },
    {
      "id": "sample-05.svg",
      "sourceId": "sample-05.svg",
      "name": "光子嫩肤做前须知",
      "title": "光子嫩肤做前须知",
      "project": "光子嫩肤",
      "ctr": 8.2,
      "features": {
        "brightness": 60,
        "saturation": 60,
        "contrast": 60,
        "warm": 50,
        "titleHook": 44,
        "hasFace": 100,
        "hasBeforeAfter": 0
      },
      "tags": [
        "人物主体"
      ]
    },
    {
      "id": "sample-06.svg",
      "sourceId": "sample-06.svg",
      "name": "祛斑项目别乱做",
      "title": "祛斑项目别乱做",
      "project": "祛斑",
      "ctr": 9.9,
      "features": {
        "brightness": 60,
        "saturation": 60,
        "contrast": 60,
        "warm": 50,
        "titleHook": 44,
        "hasFace": 100,
        "hasBeforeAfter": 100
      },
      "tags": [
        "人物主体",
        "对比展示"
      ]
    },
    {
      "id": "sample-07.svg",
      "sourceId": "sample-07.svg",
      "name": "法令纹改善真实变化",
      "title": "法令纹改善真实变化",
      "project": "抗衰/填充",
      "ctr": 10.2,
      "features": {
        "brightness": 60,
        "saturation": 60,
        "contrast": 60,
        "warm": 50,
        "titleHook": 49,
        "hasFace": 100,
        "hasBeforeAfter": 100
      },
      "tags": [
        "人物主体",
        "对比展示"
      ]
    },
    {
      "id": "sample-08.svg",
      "sourceId": "sample-08.svg",
      "name": "敏感肌能不能做医美",
      "title": "敏感肌能不能做医美",
      "project": "敏感肌",
      "ctr": 7.6,
      "features": {
        "brightness": 60,
        "saturation": 60,
        "contrast": 60,
        "warm": 50,
        "titleHook": 49,
        "hasFace": 100,
        "hasBeforeAfter": 0
      },
      "tags": [
        "人物主体"
      ]
    }
  ]
};
